### PR TITLE
Tests and plugin.yml

### PR DESCRIPTION
**Pull request by toolmantim**
Adds spellcheck, unit tests, linter, and a plugin.yml

### CODE REVIEW

**Comment by pda** [comment]
Nice work @toolmantim.

I assume for the `.buildkite/pipeline.yml` to do anything we'd need to attach this repo to a Buildkite pipeline?

**Comment by toolmantim** [comment]
You can run it via https://github.com/toolmantim/bksr — but yeah, to run on commits you'd need to set it up CI somewhere. Maybe an Elastic CI Stack in a completely separate "culture amp open source CI" AWS account? 🤔

**Comment by toolmantim** [comment]
👋🏼 Hullo! Did you want to merge this, regardless of getting it hooked up. Would love the plugin.yml change to go live.

**Comment by toolmantim** [comment]
🙏🏼

**Pull request merged**
