### PR TITLE
simplify path from aws-cli output to env

### PR DESCRIPTION
**Pull request by pda**
Previous strategy used `sed` to convert pretty-printed JSON into shell export lines, and `eval` to apply the result. Fragile and mysterious.

This PR uses aws-cli `--output text` and `--query` JMES to output just the three values we want in a stable ordering, and bash `read` to assign them to shell variables.

- [x] Seems to work.
- [x] Update mocks in tests

/cc @pilotclass

### CODE REVIEW

**Comment by pda** [comment]
```
$ docker-compose run --rm tests
 ✓ calls aws sts and exports AWS_ env vars
 ✓ failure to assume role
 ✓ calls aws sts with custom duration

3 tests, 0 failures
```

**Comment by pilotclass** [comment]
Just found this in my notifications!

**Comment by jdub** [comment]
This is a good change.

**Comment by pda** [comment]
Somebody should merge this :wink:

**Comment by pilotclass** [comment]
@matthewtapper can I suggest _you_ are a better placed to merge this than I am?

**Comment by pda** [comment]
Heyyyy thanks @pilotclass

**Pull request merged**
